<?php 

declare(strict_types = 1);

namespace inroutephp\example;

/**
 * NOTE: This file was auto-generated by inroute 2018-12-12 and should not be edited directly
 */
final class HttpRouter implements \inroutephp\inroute\Runtime\HttpRouterInterface
{
    use \inroutephp\inroute\Aura\HttpRouterTrait;

    protected function loadRoutes(\Aura\Router\Map $map): void
    {
        $mapper = new \inroutephp\inroute\Aura\RouteMapper($map);

$mapper->mapRoute(\Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['inroutephp\\inroute\\Runtime\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('inroutephp\\inroute\\Runtime\\Route')),
    ],
    null,
    [
        'inroutephp\\inroute\\Runtime\\Route' => [
            'name' => [
                'foobar',
            ],
            'routable' => [
                true,
            ],
            'httpMethods' => [
                [
                    'GET',
                ],
            ],
            'path' => [
                '/foo/{name}',
            ],
            'attributes' => [
                [
                    'scream' => true,
                ],
            ],
            'serviceId' => [
                'inroutephp\\example\\Controller\\Controller',
            ],
            'serviceMethod' => [
                'foo',
            ],
            'middlewareServiceIds' => [
                [
                    'inroutephp\\example\\ScreamMiddleware',
                ],
            ],
        ],
    ],
    $o[0],
    []
));
$mapper->mapRoute(\Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['inroutephp\\inroute\\Runtime\\Route'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('inroutephp\\inroute\\Runtime\\Route')),
    ],
    null,
    [
        'inroutephp\\inroute\\Runtime\\Route' => [
            'name' => [
                'index',
            ],
            'routable' => [
                true,
            ],
            'httpMethods' => [
                [
                    'GET',
                ],
            ],
            'path' => [
                '/',
            ],
            'serviceId' => [
                'inroutephp\\example\\Controller\\IndexController',
            ],
            'serviceMethod' => [
                'index',
            ],
        ],
    ],
    $o[0],
    []
));
    }
}
